---
plugin: aws_ec2
aws_access_key: {{lookup('env', 'AWS_ACCESS_KEY_ID')}}
aws_secret_key: {{lookup('env', 'AWS_SECRET_ACCESS_KEY')}}
regions:
  - us-east-1
keyed_groups:
  - key: tags_group
    prefix: webserver
