---
- name: update repo
  apt:
    update_cache: yes
- name: set hostname
  hostname: 
    name: bastion
- name: install nginx
  apt:
    name: nginx
    state: latest
- name: enable nginx
  service:
    name: nginx
    enabled: yes
- name: Remove default file from nginx
  file:
    path: /etc/nginx/sites-available/default
    state: absent
- name: Remove default file from nginx
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
- name: create loadbalancer.conf file
  template: src=loadbalancer.conf dest=/etc/nginx/sites-available/loadbalancer.conf
- name: Create a symbolic link
  ansible.builtin.file:
    src: /etc/nginx/sites-available/loadbalancer.conf
    dest: /etc/nginx/sites-enabled/loadbalancer.conf
    owner: www-data
    group: www-data
    state: link


