---
- hosts: all 
  become: yes
  - name: Update and upgrade
    remote_user: ubuntu
    apt:
      update_cache: yes

- hosts: bastion
  remote_user: ubuntu
  roles:
  - bastion

- hosts: webserver
  remote_user: ubuntu
  roles:
    - webserver